### ISSUE TITLE
如何在手机上使用？

### ISSUE THREAD

**Issue by wuxueshuan** [aspose-words/Aspose.Words-for-Java#100]
如何在手机上使用？implementation(group: 'com.aspose', name: 'aspose-words', version: '22.12', classifier: 'jdk17')导入以后引用不到里面的包

**Comment by AlexNosk** [comment]
@wuxueshuan  你应该使用 [Aspose.Words for Android via Java](https://releases.aspose.com/words/androidjava/).  
请参阅我们的文档以获取更多信息：
<https://docs.aspose.com/words/java/aspose-words-for-android-via-java-limitations-and-api-differences/>

另外，请注意，主要的支持地点是 [Aspose.Words support forum](https://forum.aspose.com/c/words/8).
