### ISSUE TITLE
can I use Aspose in Linux

### ISSUE THREAD

**Issue by laodaobazi** [aspose-words/Aspose.Words-for-Java#24]
what can I do use Aspose in CentOS ?

**Comment by saqib-razzaq-aspose** [comment]
Yes, you can use Aspose in Linux. Please view this page (http://www.aspose.com/docs/display/wordsjava/System+Requirements) for system requirements for Aspose.Words for Java.

After setting up JDK and an IDE (which supports Maven), you can directly open this project (https://github.com/asposewords/Aspose_Words_Java/tree/master/Examples).

To use in your own application, please add reference to Aspose binaries using jar (from downloads) or Maven (see pom.xml in this repository).

**Comment by laodaobazi** [comment]
Thank you very much @saqib-razzaq-aspose
