### ISSUE TITLE
Non-configurable setting in Aspose_Words_Java_for_Ruby

### ISSUE THREAD

**Issue by justintanner** [aspose-words/Aspose.Words-for-Java#30]
I'm trying to use `asposewordsjavaforruby` with the Aspose Words for Java.

In the file:

`Aspose.Words-for-Java/Plugins/Aspose_Words_Java_for_Ruby/lib/asposewordsjavaforruby.rb`

I see the following line:

`license = Rjb::import('com.aspose.api.License').new()`

Doesn't integrate with correctly load the license file, I had to change it to:

`license = Rjb::import('com.aspose.words.License').new()`

Is this the correct?

Please advise.

**Comment by fahadadeel** [comment]
Thanks Justin Tanner for pointing out the issue.  Yes you are correct it should be 
license = Rjb::import('com.aspose.words.License').new()
We will fix this bug and update our repo as well.

Thanks

**Comment by fahadadeel** [comment]
This issue has been fixed and updated on our repo.

**Comment by bmulholland** [comment]
@fahadadeel While the issue is fixed in the repo, the published gem still has this bug. Considering the recommended way of using the code is via the gem, I don't think this bug is actually fixed.

**Comment by aspose-words** [comment]
@bmulholland,
I am afraid, we are not maintaining this plugin since long. So, please use the [latest version of Aspose.Words for Java](https://artifact.aspose.com/webapp/#/artifacts/browse/tree/General/repo/com/aspose/aspose-words/18.4) i.e. **18.4** and try to fix the issue by yourself. We apologize for any inconvenience.

**Comment by aspose-words** [comment]
@bmulholland,

Thanks for sharing workaround in [this post](https://forum.aspose.com/t/aspose-causes-ruby-segfualt/174108/12?u=awais.hafeez). We are copying the workaround details here which may help other developers who are facing the same problem:

> We have found a workaround for this issue: we initialize Aspose once in a rails initializer rather than initializing during each request. This avoids the segfault because the sequence of request->initialize doesn’t happen. If anyone reads this in the future, if your production server uses worker forking then you’ll need to initialize Aspose AFTER the fork.
> 
> We’ve done the initialization directly without the gem. Our initializer now looks something like this:
> 
> ```
> Rjb::load(Dir.glob(Rails.root.join("lib", "aspose", "*.jar").to_s).join(':'), ['-Djava.awt.headless=true'])
> 
> fstream = Rjb::import('java.io.FileInputStream').new(Rails.root.join("lib", "aspose", "Aspose.Words.lic").to_s)
> 
> license = Rjb::import('com.aspose.words.License').new
> license.setLicense(fstream)
> ```
> This code runs immediately (during init) in test/dev environments. On production (& staging), it runs after Passenger starts its worker process.
