### ISSUE TITLE
Apose Words Java for Ruby does not load setting file

### ISSUE THREAD

**Issue by justintanner** [aspose-words/Aspose.Words-for-Java#31]
`Aspose_Words_Java_for_Ruby` does not load settings from `config/aspose.yml`. 

Setting such as `jar_dir` and `license_path` are not being applied.

**Comment by fahadadeel** [comment]
Hello Justin Tanner,
Sorry for the inconvenience you are facing, we are looking this issue and will update you soon.

Thanks

**Comment by fahadadeel** [comment]
Hello Justin Tanner,
config/aspose.yml is only for the rails applications. If you see method load_aspose_jars, if it doesn't get jar_dir from the config folders, it loads it from the default path, which in this case is the jars folder. 

jardir = File.join(File.dirname(File.dirname(**FILE**)), 'jars', '*_', '_.jar')

Thanks

**Comment by justintanner** [comment]
I see. It would be nice be able to choose which folder the jar file is located ( same with the license file ).

**Comment by fahadadeel** [comment]
Hello Justin Tanner,

Thanks for the suggestion.
Aspose provides the provision to our users to change the source code according to requirements.
You can easily configure the location of your jar file by simply replacing the nil with your jar folder in below lines:

aspose_jars_dir = Asposewordsjavaforruby.aspose_words_config ? Asposewordsjavaforruby.aspose_words_config[‘jar_dir’] : nil
aspose_license_path = Asposewordsjavaforruby.aspose_words_config ? Asposewordsjavaforruby.aspose_words_config[‘license_path’] : nil

Thanks,
