### ISSUE TITLE
Examples cannot be executed

### ISSUE THREAD

**Issue by sebastianfrohn** [aspose-words/Aspose.Words-for-Java#36]
I checked out the repository and imported the project as described in http://www.aspose.com/docs/display/wordsjava/How+to+Run+the+Examples to Intellij.

When I try to start any of these examples, I get an error in BuildTableFromDataTable.java in line 33:

```
		// Retrieve the data from our data source which is stored as a DataTable.
		DataTable dataTable = getEmployees(databaseDir);
```
This seems to be a not defined static function with a variable wich is not defined anywhere, too. A full-text-search in the whole project does not find any declaration.

Are there some installation-steps missing or is it a bug? Or do I need code from additional repositories?

**Comment by sohail-aspose** [comment]
Hi Sebastian Frohn,

Thank you for bringing this to our attention. 

> Are there some installation-steps missing or is it a bug? Or do I need code from additional repositories?

It was a bug and has been fixed and now all examples are running fine in IntelliJ IDEA.
