### ISSUE TITLE
Jypype find and replace example not working

### ISSUE THREAD

**Issue by Chase842** [aspose-words/Aspose.Words-for-Java#38]
The example on Github here:
https://github.com/aspose-words/Aspose.Words-for-Java/blob/master/Plugins/Aspose_Words_Java_for_Python/tests/quickstart/findandreplace/findandreplace.py

and the example on Aspose's website here:
http://www.aspose.com/docs/pages/viewpage.action?pageId=434471204

Both examples are not working for me.

**Comment by fahadadeel** [comment]
Hello Chase842,

Find and Replace method for Java APIs has been updated, please use following example as a reference, which is updated on our GitHub repository as well.

`class FindAndReplace:

    def main(self,srcDocFile,outputDocFile,searchString,replaceString):

        Document =jpype.JClass("com.aspose.words.Document")
        FindReplaceDirection =jpype.JClass("com.aspose.words.FindReplaceDirection")
        FindReplaceOptions =jpype.JClass("com.aspose.words.FindReplaceOptions")

        doc = Document(srcDocFile)

        print "Original document text: " + doc.getRange().getText()

        doc.getRange().replace(searchString, replaceString, FindReplaceOptions(FindReplaceDirection.FORWARD))
        # Check the replacement was made.

        print "Document text after replace: " + doc.getRange().getText()

        # Save the modified document.
        doc.save(outputDocFile)`
