### ISSUE TITLE
Java : Find and Hightlight is not working. Index out of bound

### ISSUE THREAD

**Issue by chandanluthra** [aspose-words/Aspose.Words-for-Java#42]
While trying to run the find and highlight, Index out of bound exception is coming.

I executed following example. 

https://github.com/aspose-words/Aspose.Words-for-Java/blob/master/Examples/src/main/java/com/aspose/words/examples/programming_documents/find_replace/FindAndHighlightText.java

**Comment by tahir-manzoor** [comment]
Hi there,
Thanks for your inquiry. We have fixed this issue. Please download the code again.
