### ISSUE TITLE
Ruby Segfault

### ISSUE THREAD

**Issue by bmulholland** [aspose-words/Aspose.Words-for-Java#45]
I have found a Ruby segfault when using together with rails, cucumber, and chrome. Repro at https://github.com/bmulholland/aspose-segfault

This is crashing our test suite about 25% of the time.

**Comment by bmulholland** [comment]
Is there a better way to report bugs?

**Comment by tahir-manzoor** [comment]
@bmulholland, We are investigating this issue and will get back to you soon.

**Comment by tahir-manzoor** [comment]
We have logged this issue as WORDSJAVA-1765 in our issue tracking system. We will inform you once this issue is resolved.

**Comment by AlexNosk** [comment]
The issue was resolved in 18.5 version.
