### ISSUE TITLE
下载后测试，生成的html内除文档内容外有企业logo(Aspose)图片

### ISSUE THREAD

**Issue by boluoshu** [aspose-words/Aspose.Words-for-Java#47]
这是为什么，是因为没有用License吗

**Comment by aspose-words** [comment]
@seven-hu-go ,
是的，这是因为您在评估模式下使用Aspose.Words（未设置许可证）。 如果您想在没有评估版本限制的情况下测试Aspose.Words，您还可以申请30天的临时许可证。 请参阅：
[如何获得临时许可证？](https://purchase.aspose.com/temporary-license)

**Comment by boluoshu** [comment]
Thank you very much

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Aspose.Words Product Family <notifications@github.com>
发送时间: Tuesday, September 11, 2018 4:06:16 PM
收件人: aspose-words/Aspose.Words-for-Java
抄送: seven-hu-go; Mention
主题: Re: [aspose-words/Aspose.Words-for-Java] 下载后测试，生成的html内除文档内容外有企业logo(Aspose)图片 (#47)


@seven-hu-go<https://github.com/seven-hu-go> ,
Yes, this is because you are using Aspose.Words in evaluation mode (without setting the license). If you want to test Aspose.Words without the evaluation version limitations, you can also request a 30-day Temporary License. Please refer to How to get a Temporary License?<https://purchase.aspose.com/temporary-license>

―

**Comment by aspose-words** [comment]
@seven-hu-go,
如果您有进一步的询问或需要任何帮助，请告诉我们。
请随时在以下Aspose.Words论坛中发布您的查询：
https://forum.aspose.com/c/words

**Comment by boluoshu** [comment]
好的，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Aspose.Words Product Family <notifications@github.com>
发送时间: Tuesday, September 11, 2018 7:24:27 PM
收件人: aspose-words/Aspose.Words-for-Java
抄送: seven-hu-go; Mention
主题: Re: [aspose-words/Aspose.Words-for-Java] 下载后测试，生成的html内除文档内容外有企业logo(Aspose)图片 (#47)


@seven-hu-go<https://github.com/seven-hu-go>,
如果您有进一步的询问或需要任何帮助，请告诉我们。
请随时在以下Aspose.Words论坛中发布您的查询：
https://forum.aspose.com/c/words

―
