### ISSUE TITLE
导出word着重号

### ISSUE THREAD

**Issue by yaphot** [aspose-words/Aspose.Words-for-Java#48]
导出word着重号怎么写？》

**Comment by awaishafeez** [comment]
@yaphot,

请压缩并将显示所需输出的预期文档上传到Dropbox或任何其他文件托管服务，并在此提供下载链接以供我们参考。 您可以使用MS Word创建预期文档。 然后，我们将调查您的预期文档的结构，并通过使用Aspose.Words为您提供实现相同的代码。

**Comment by yaphot** [comment]
[着重号.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/2694891/default.docx)

**Comment by yaphot** [comment]
> @yaphot,
> 
> 请压缩并将显示所需输出的预期文档上传到Dropbox或任何其他文件托管服务，并在此提供下载链接以供我们参考。 您可以使用MS Word创建预期文档。 然后，我们将调查您的预期文档的结构，并通过使用Aspose.Words为您提供实现相同的代码。

已上传，谢谢！

**Comment by awaishafeez** [comment]
@yaphot,

我们已在问题跟踪系统中记录您的要求。 我们将在Aspose.Words中添加一个功能，以支持“Emphasis Mark”字体设置。 您的票号是WORDSNET-13983。 我们将进一步研究此要求的详细信息，并随时向您通报此问题的最新状态：

**Comment by yaphot** [comment]
OK.thanks

**Comment by yaphot** [comment]
@awaishafeez 
如何将 <w:rPr> <w:em w:val="dot"/> </w:rPr>   写入word中呢？

**Comment by aspose-com-gists** [comment]
@yaphot ,

我担心，目前这是不可能的。

在DOCX格式中，这是<w:em w:val= />内的<w:rPr>元素。 值可以是'CIRCLE'，'COMMA'，'DOT'，'NONE'和'underdot'。

在DOC格式中，这是sprmCKcd（0x2A34），其操作数必须是以下值之一：

- 0x00 - No emphasis
- 0x01 - Solid circle
- 0x02 - Comma above
- 0x03 - Circle above
- 0x04 - Solid circle below 

在RTF格式中，这些是字体格式属性的以下控制字：
'\ accnone'，'\ accdot'，'\ acccomma'，'\ acccircle'和'\ accunderdot'。

一旦此问题得到解决，我们会立即通知您。 很抱歉给您带来不便。

**Comment by AlexNosk** [comment]
@yaphot The feature you have asked about is already available in the latest version of Aspose.Words. Please see [Font.EmphasisMark](https://apireference.aspose.com/words/net/aspose.words/font/properties/emphasismark) property.
You can download the latest version of Aspose.Words for Java from [here](https://downloads.aspose.com/words/java).
