### ISSUE TITLE
Create Document via input stream results in blank saved document

### ISSUE THREAD

**Issue by spoco2** [aspose-words/Aspose.Words-for-Java#49]
I just spent ages trying to work out why my DOCX --> PDF files were ending up blank.

`InputStream fileStream = new FileInputStream(fileToConvert);`
`Document doc = new Document(fileStream);`
`doc.save(targetFile.getAbsolutePath(), SaveFormat.PDF);`

Results in blank document

`Document doc = new Document(fileToConvert.getAbsolutePath());`
 `doc.save(targetFile.getAbsolutePath(), SaveFormat.PDF);`

Works

No errors, nothing to suggest the former wouldn't work, it just creates a blank document. 

Grrr.

(I had the filestream as I needed that to be able to use your FileFormatInfo to throw an encrypted error for encrypted files, and figured as I had it I may as well give it to the document constructor)

**Comment by awaishafeez** [comment]
@spoco2 ,
It looks like you need to rewind the InputStream position back to zero so it is ready for Aspose.Words' Document constructor to read it from the start position. Or you can close the InputStream and then re-instantiate by using the following code:
```
InputStream in = new FileInputStream(dataDir + filename);
Document doc = new Document(in);
```

**Comment by spoco2** [comment]
@awaishafeez Aaaah! Ok. That makes sense. I guess that opens the question then, is there ever any case where someone would want to use `new Document(inputStream)` with anything but it reading from the start? If not, would it make sense for the constructor to rewind the inputStream before reading it?

**Comment by awaishafeez** [comment]
@spoco2,
I am afraid, the Document constructor of Aspose.Words for Java starts reading the InputStream from the current position to the end. It does not rewind and does not close the stream after reading.

However, we have logged your requirement in our issue tracking system. Your ticket number is **WORDSJAVA-1971**. We will further look into the details of this requirement and will keep you updated on the status of this issue. We apologize for any inconvenience.

**Comment by spoco2** [comment]
Thanks for the reply. Our use case is all fine here, I just went back to using it directly from the filename and it works fine. It was just very unclear why the stream was causing a blank document.

**Comment by aspose-com-gists** [comment]
@spoco2,
It is great that you were to resolve this issue on your end.

Regarding WORDSJAVA-1971, we have completed the work on your issue and concluded to close this issue as ‘Not a Bug’. Please see the following analysis details:

1. We unfortunately could not reproduce the exact bug on our end. The code snippet you provided works fine on our end - we get just the converted PDF document. Probably, you read FileInputStream just before passing it to the Document() constructor.

2. Many InputStreams of Java cannot rewind. InputStream contract does not contain get/set(position) methods or something similar. So, Document(InputStream) constructor does not even try to rewind the stream.
