### ISSUE TITLE
aspose  word转pdf linux系统上很慢

### ISSUE THREAD

**Issue by lllfx** [aspose-words/Aspose.Words-for-Java#53]
同样的代码和word文件，在windows 讲word转成pdf只需要2s左右，在linux上需要200s。请问aspose是不是用了windows上某些库？

**Comment by lllfx** [comment]
解决了，主要是doc中资源的问题。将资源定义为skip就可以了。

**Comment by liu-zifan** [comment]
> 解决了，主要是doc中资源的问题。将资源定义为skip就可以了。

你好，请问怎么定义为skip

**Comment by AlexNosk** [comment]
@liu-zifan  您可以使用IResourceLoadingCallback来在加载文档时跳过加载外部资源。
https://apireference.aspose.com/words/java/com.aspose.words/resourceloadingaction#SKIP
