### ISSUE TITLE
com.aspose.words.License.isLicensed() is deprecated

### ISSUE THREAD

**Issue by ZCHWorld** [aspose-words/Aspose.Words-for-Java#55]
com.aspose.words.License.isLicensed() is deprecated, I can't find an alternative, who can tell me?thank.

**Comment by awaishafeez** [comment]
@ZCHWorld,
I am afraid, there is no alternative. License.setLicense method throws an exception if license is invalid. You can use try-catch block to look for any exceptions. Hope, this helps.

**Comment by ZCHWorld** [comment]
amazing!
