### ISSUE TITLE
word 转 pdf 绘图工具所做的 图片丢失 着重号丢失

### ISSUE THREAD

**Issue by cuixiaoyan** [aspose-words/Aspose.Words-for-Java#57]
![image](https://user-images.githubusercontent.com/35671835/63082995-36558380-bf7a-11e9-877f-1521e80b000d.png)
丢失部分是绘图工具 所绘制的图片 直接引入的图片 是没有问题的
`Document doc = new Document(inPath); // Address是将要被转化的word文档
			doc.save(os, SaveFormat.PDF);// 全面支持DOC, DOCX, OOXML, RTF HTML, OpenDocument, PDF,`
[a.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/3504813/a.docx)
![image](https://user-images.githubusercontent.com/35671835/63083163-9fd59200-bf7a-11e9-9cc6-e05349fed486.png)
着重号问题丢失 
![image](https://user-images.githubusercontent.com/35671835/63083206-bed42400-bf7a-11e9-9bf7-b278f8fd6f75.png)

因为所用到的word 文档比较复杂 这里转换 成pdf 或者 图片 都会出现上述问题

**Comment by awaishafeez** [comment]
@cuixiaoyan ,
在使用最新版本的Aspose.Words for .NET（即19.8）进行初步测试后，我们无法在最终重现此问题。 请使用以下简单代码查看我们从您的DOCX文件生成的输出PDF（[19.8.pdf](https://github.com/aspose-words/Aspose.Words-for-Java/files/3507990/19.8.pdf)）：
```
Document doc = new Document("E:\\Temp\\a.docx");
doc.Save("E:\\Temp\\19.8.pdf");
```
所以，请升级到最新版本，即19.8。 希望这可以帮助。

**Comment by cuixiaoyan** [comment]
@awaishafeez 你好 我已经修复了图片丢失的问题 我是java 的  但是着重号显示问题仍然存在 如你所见 这个功能是比较有用的 能否在代码方面进行修改

**Comment by awaishafeez** [comment]
@cuixiaoyan ,

我已使用“另存为”命令使用MS Word 2019将您的a.docx文档转换为PDF foromat，并在此处附加PDF文件供您参考。
[msw-2019.pdf](https://github.com/aspose-words/Aspose.Words-for-Java/files/3511642/msw-2019.pdf)

您是否在此MS Word 2019生成的PDF中看到了同样的问题？

如果是，请同时提供一个比较屏幕截图，突出显示Aspose.Words生成的PDF文件中有问题的区域，关于MS Word 2019生成的PDF文件，并将其附在此处供我们参考。 请指出此问题确切存在的问题。 然后，我们将进一步调查此问题，并为您提供更多信息。 谢谢你的合作。

**Comment by cuixiaoyan** [comment]
@awaishafeez 这个在转换为pdf时 直接报错 
[转换直接就报错.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/3513863/default.docx)
![image](https://user-images.githubusercontent.com/35671835/63233881-38169400-c265-11e9-9cd3-15f7122068c1.png)
我并不知道问题原因 只有这个文档会有这个问题

**Comment by awaishafeez** [comment]
@cuixiaoyan ,

在使用[Aspose.Words for Java的最新版本](https://downloads.aspose.com/words/java)（即19.8）进行初步测试后，我们无法在最终重现此问题（请参阅输出 [awjava-19.8.pdf](https://github.com/aspose-words/Aspose.Words-for-Java/files/3514147/awjava-19.8.pdf)）。 我们使用以下代码在Windows 10计算机（Java 8）上进行了测试：

```
文档doc = new Document（“E：\\ Temp \\ default（1）.docx”）;
doc.updatePageLayout（）;
doc.save（ “E：\\温度\\ awjava-19.8.pdf”）;
```

**Comment by cuixiaoyan** [comment]
@awaishafeez 我所使用的版本为 19.1 word 转换图片出现如下问题
![image](https://user-images.githubusercontent.com/35671835/63561672-652cb480-c58d-11e9-9e61-5bde72ff1528.png)
使用word转换pdf是不会出现所述问题 望解答

**Comment by awaishafeez** [comment]
@cuixiaoyan ,
请升级到最新版本的Aspose.Words for Java，即19.8
https://downloads.aspose.com/words/java

如果问题仍然存在，请压缩并上传新的有问题的Word文档和相应的PDF文件，在此处显示不需要的行为以进行测试。 然后，我们将在最后调查此问题，并为您提供更多信息。

_附： 我担心，我们不支持旧版本的Aspose.Words。 另请注意，我们不会为旧版本的Aspose API提供任何修补程序或补丁。 所有修复程序和新功能总是添加到我们的API的新版本中。 所以，请升级到最新版本，即19.8。 希望这可以帮助。_

**Comment by awaishafeez** [comment]
@cuixiaoyan,
您是否设法解决了问题，或者您是否还需要帮助？ 如果问题得到解决，那么我们将解决此问题。

**Comment by cuixiaoyan** [comment]
@awaishafeez  你好已经解决 谢谢你的热心回复

**Comment by Allen09** [comment]
> @awaishafeez 你好 我已经修复了图片丢失的问题 我是java 的 但是着重号显示问题仍然存在 如你所见 这个功能是比较有用的 能否在代码方面进行修改

麻烦问哈。图片丢失的问题是如何解决的呢。

**Comment by awaishafeez** [comment]
@Allen09 ,

您是否尝试过最新的（20.12）版本的Aspose.Words for Java？ 如果问题仍然存在，那么建议您将查询发布在Aspose.Words论坛中，因为技术支持的主要途径仅是通过我们的论坛。
https://forum.aspose.com/c/words/8

也请ZIP并上传您输入的Word文档和Aspose.Words生成的输出文件，其中显示了不良行为，用于测试。 另请创建一个比较屏幕截图，突出显示Aspose.Words生成的输出中的问题区域，并将其附加到您将在Aspose.Words论坛中创建的线程中。 然后，我们将对此进行调查，并为您提供更多信息。
