### ISSUE TITLE
两个doc文档合并，合并后字体大小变了，这是什么原因？

### ISSUE THREAD

**Issue by wangruofeianccl** [aspose-words/Aspose.Words-for-Java#61]
合并前：
![image](https://user-images.githubusercontent.com/25164718/72205431-df6ac080-34bd-11ea-8080-1b60d002b6e0.png)
合并后:
![image](https://user-images.githubusercontent.com/25164718/72205470-51430a00-34be-11ea-8408-82de78a3164e.png)

**Comment by AlexNosk** [comment]
Thanks for your request. Could you please attach your input and output documents for testing and provide code to reproduce the problem? We will check the issue and provide you more information.

**Comment by AlexNosk** [comment]
No feedback from the customer. Close the issue.
