### ISSUE TITLE
words convert to html problem

### ISSUE THREAD

**Issue by colddew** [aspose-words/Aspose.Words-for-Java#63]
i paste a png table picture in the words document, but when i use aspose-words and convert words to html, the text in the picture rotate 90 degrees. i wonder if I need to set some parameters, or it is a bug

original words
http://60.179.33.39:81/e/file/download?code=57b6ec48b1fa3a67&id=17937

original snapshot
![image](https://user-images.githubusercontent.com/6032545/75272696-5a532500-5839-11ea-918f-9388dbcbea5c.png)

convert snapshot
![image](https://user-images.githubusercontent.com/6032545/75272809-8a022d00-5839-11ea-89ee-1796621c2186.png)

**Comment by colddew** [comment]
aspose-words version is 18.5.0718

**Comment by AlexNosk** [comment]
Could you please reattach the original document. The link you have provided is not valid anymore. We will investigate the problem and provide you more information.

**Comment by AlexNosk** [comment]
No feedback. Closed the issue.
