### ISSUE TITLE
UpdateFields BUG

### ISSUE THREAD

**Issue by Deathef** [aspose-words/Aspose.Words-for-Java#66]
I call the method getMailMerge().execute() after updateFields, then it comes a bug like this
![demo1](https://user-images.githubusercontent.com/32616338/86588690-c64f5200-bfbe-11ea-895d-55244b18a67d.png)
![demo2](https://user-images.githubusercontent.com/32616338/86588704-cb140600-bfbe-11ea-94fc-c13bb7bababf.png)
```java
        String resourceWordPath = "demo.docx";
        String targetWordPath = "demo1.docx";
        try {
            WordToPdfUtils.getLicense();
            Document doc = new Document(resourceWordPath);
            doc.getMailMerge().execute(new String[]{"name"}, new String[]{"111"});
            doc.updateFields();
            doc.save(targetWordPath);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by AlexNosk** [comment]
@Deathef Could you please attach the source template, the output document and the desired output? We will check the issue and provide you more information.

**Comment by Deathef** [comment]
@AlexNosk  annex is  the source template, the output document and the desired output
[demo.zip](https://github.com/aspose-words/Aspose.Words-for-Java/files/4893984/demo.zip)

**Comment by AlexNosk** [comment]
@Deathef Thank you for additional information. I managed to reproduce the problem on my side and logged the issue as **WORDSNET-20778** in our bug traching system We will let you know once the issue is resolved.

**Comment by AlexNosk** [comment]
@Deathef MS Word applies restartNumberingAfterBreak attribute to each list in document during mail merge. Aspose.Words also follows this behavior. So this is considered as Not a bug.
You may use the following code snippet to retain original list numbering:
``` java
Document doc = new Document(resourceWordPath);

Map<List,Boolean> lists = new HashMap<List,Boolean> ();
for (List list : doc.getLists())
    lists.put(list,list.isRestartAtEachSection());

doc.getMailMerge().execute(new String[]{"name"}, new String[]{"111"});

for (Map.Entry<List, Boolean> pair : lists.entrySet())
    pair.getKey().isRestartAtEachSection(pair.getValue());

doc.updateFields();
doc.save(targetWordPath);
```

Please let me know if the proposed workaround works for you and the issue can be closed.

**Comment by Deathef** [comment]
@AlexNosk According to the code you provided, we successfully solved the problem;
