### ISSUE TITLE
builder.insertChart() How can  set different colors

### ISSUE THREAD

**Issue by tanhuang2016** [aspose-words/Aspose.Words-for-Java#72]
The sample code
```java
public void HideChartAxis(String dataDir) throws Exception
{
    // ExStart:HideChartAxis
    Document doc = new Document();
    DocumentBuilder builder = new DocumentBuilder(doc);

    Shape shape = builder.insertChart(ChartType.COLUMN, 432, 252);
    Chart chart = shape.getChart();

    // Clear the chart's demo data series to start with a clean chart.
    chart.getSeries().clear();

    // Add a custom series with categories for the X-axis, and respective decimal values for the Y-axis.
    chart.getSeries().add("AW Series 1",
            new String[]{"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"},
            new double[]{1.2, 0.3, 2.1, 2.9, 4.2});

    // Hide the axis
    chart.getAxisY().setHidden(true);

    dataDir = dataDir + "HideChartAxis_out.docx";
    doc.save(dataDir);
    //ExEnd:HideChartAxis
    System.out.println("\nY Axis of chart has been hidden successfully. \nFile saved at " + dataDir);
}
```
like this
![image](https://user-images.githubusercontent.com/38677722/120095475-c321ff00-c158-11eb-98db-774d0aac7bc1.png)

how to set different colors
![image](https://user-images.githubusercontent.com/38677722/120095529-185e1080-c159-11eb-8af9-502aaf6355e8.png)

**Comment by AlexNosk** [comment]
@tanhuang2016 The requested feature will be available in the next version of Aspose.Words through the [ChartDataPoint ](https://apireference.aspose.com/words/java/com.aspose.words/ChartDataPoint)class. The corresponding issue number is **WORDSNET-12275**. We will let you know once the next version is available (in a week or two).

**Comment by AlexNosk** [comment]
The issues you have found earlier (filed as WORDSNET-12275) have been fixed in this Aspose.Words 21.6. You can download it here:
https://downloads.aspose.com/words/java
Also see the release notes for code example.
https://docs.aspose.com/words/java/aspose-words-for-java-21-6-release-notes/#implemented-ability-to-set-fill-and-stroke-formatting-for-chart-series-data-points-and-markers
