### ISSUE TITLE
word coverts to pdf table  direct error

### ISSUE THREAD

**Issue by kebenart** [aspose-words/Aspose.Words-for-Java#73]
When the document is set to landscape, the wrong text direction will appear when going to PDF
![image](https://user-images.githubusercontent.com/33311918/124057477-205fe780-da5a-11eb-8076-f2e779846762.png)

error
![image](https://user-images.githubusercontent.com/33311918/124057536-379ed500-da5a-11eb-9dd2-7738e00a2dbe.png)

**Comment by AlexNosk** [comment]
@kebenart Could please attach your input and output documents here for testing and provide the code that allows to reproduce the problem. We will check the issue and provide you more information.

**Comment by AlexNosk** [comment]
There is no feedback. Close the issue. If the issue still persist, please feel free to open another one.
