### ISSUE TITLE
Table HorizontalMerge is zero

### ISSUE THREAD

**Issue by Pantianmiao** [aspose-words/Aspose.Words-for-Java#75]
Word inner Table HorizontalMerge always is zero. Like this:
![image](https://user-images.githubusercontent.com/26376043/129715479-85713021-a638-4bb5-ae3e-fd402460c699.png)

**Comment by AlexNosk** [comment]
@Pantianmiao In MS Word documents rows are independent, that means each row in the table can have any number of cells of any width. Most likely in your case horizontally merged cells are emulated by adjusting width of individual cells. 
Could you please attach your document here for testing, I will take a look and provide you more information.

**Comment by AlexNosk** [comment]
No additional feedback. Close.
