### ISSUE TITLE
how to handle special symbol wingdings when convert to pdf

### ISSUE THREAD

**Issue by NigoUP** [aspose-words/Aspose.Words-for-Java#76]
word:
![image](https://user-images.githubusercontent.com/16929651/146700826-5189cdae-af17-4b51-aa68-cb53a10a9f3a.png)

pdf:
![image](https://user-images.githubusercontent.com/16929651/146700868-2c38c284-48ed-4e46-85c7-2bc189834929.png)

when my word converts to pdf, the symbol wingdings is wrong, how can I do with this word document.

**Comment by zhouxq** [comment]
假期自动回复。

**Comment by AlexNosk** [comment]
@NigoUP It looks like fonts used in your source document are not available in the environment where document is converted to PDF. Please note to properly layout and render document [Aspose.Words requires fonts](https://docs.aspose.com/words/java/using-truetype-fonts/) used in your document. 
If after installing the fonts the problem still persist, please attach your document here for testing. We will check the issue and provide you more information.
