### ISSUE TITLE
word转pdf的时候，可以让修订记录显示吗？

### ISSUE THREAD

**Issue by qingzao** [aspose-words/Aspose.Words-for-Java#79]
word转pdf，修订记录都没有了，有什么办法可以让修订记录显示吗？都是些插入了。。删除了。。的记录

**Comment by AlexNosk** [comment]
@qingzao 您可以使用 [RevisionOptions ](https://apireference.aspose.com/words/java/com.aspose.words/RevisionOptions)类来控制在布局过程中如何处理文档修订。 如果您需要更多帮助，请告诉我。
