### ISSUE TITLE
为什么docx文档转pdf时，pdf中tif图片显示异常

### ISSUE THREAD

**Issue by doesitsworks** [aspose-words/Aspose.Words-for-Java#81]
JDK8中使用的20.12-jdk17版本在word文档转pdf时，word中包含有tif格式的图片，转换后的pdf中的图片多了黑白底纹
![微信图片_20220424203308](https://user-images.githubusercontent.com/104305110/164976751-c267c4f3-4930-48a5-a323-bca741bcfefe.png)
![微信图片_20220424203313](https://user-images.githubusercontent.com/104305110/164976778-6ec64368-5deb-42cb-9f0e-3324cff2b1a7.png)

**Comment by zhouxq** [comment]
假期自动回复。

**Comment by AlexNosk** [comment]
@doesitsworks 您能否附上您的输入和输出文件以进行测试？ 我们将检查问题并为您提供更多信息。

**Comment by doesitsworks** [comment]
> @doesitsworks 您能否附上您的输入和输出文件以进行测试？ 我们将检查问题并为您提供更多信息。
[test.zip](https://github.com/aspose-words/Aspose.Words-for-Java/files/8552534/test.zip)
测试的word文档和tif图片，请帮解决！

**Comment by AlexNosk** [comment]
@doesitsworks 感谢您提供更多信息。 为了更正，该问题已记录为 **WORDSJAVA-2722**。 我们会及时通知您，并在问题解决后通知您。

**Comment by ioooooooq** [comment]
java中docx转pdf 为什么红头文件不见了
![image](https://user-images.githubusercontent.com/61259097/174922992-c731143d-0203-47ee-b04b-cb5b5bc5b71e.png)
![image](https://user-images.githubusercontent.com/61259097/174923075-21860204-b970-4fed-91a3-5495652fb014.png)

**Comment by AlexNosk** [comment]
@doesitsworks The issue you have fond earlier has been resolved in the latest version of [Aspose.Words for Java](https://releases.aspose.com/words/java/). Also, please see our documentation to learn more about options Aspose.Words dependencies:
<https://docs.aspose.com/words/java/system-requirements/#optional-dependencies>
