### ISSUE TITLE
fixed header on each page of the table

### ISSUE THREAD

**Issue by JiangHao-1** [aspose-words/Aspose.Words-for-Java#82]
fixed header on each page of the table

**Comment by JiangHao-1** [comment]
I have a requirement to implement a table through coding. My data may appear on multiple pages. I want the data on each page to automatically have a header. Note that it is not configured through a template

**Comment by AlexNosk** [comment]
@JiangHao-1 You can achieve this by specifying [RowFormat.HeadingFormat](https://apireference.aspose.com/words/java/com.aspose.words/rowformat#HeadingFormat) property.
Please see our documentation for more information:
<https://docs.aspose.com/words/java/working-with-columns-and-rows/#specify-rows-to-repeat-on-subsequent-pages-as-header-rows>
