### ISSUE TITLE
docx文件中表格每行高会增加，怎么处理呢？aspose word 15 

### ISSUE THREAD

**Issue by xiaoxuhuicode** [aspose-words/Aspose.Words-for-Java#83]

**Comment by xiaoxuhuicode** [comment]
aspose-word-jdk16-15.8.0

**Comment by AlexNosk** [comment]
@xiaoxuhuicode 您能否详细说明您的问题？ 这个问题不是很清楚。 请附上您的输入、输出和预期输出文档以及允许重现问题的代码。 我们将检查该问题并为您提供更多信息。

**Comment by xiaoxuhuicode** [comment]
aspose-word-jdk16-15.8.0版本doc文件加水印后表格正常显示。docx文件加水印后表格中每行行高会变高，怎么处理

**Comment by AlexNosk** [comment]
@xiaoxuhuicode 您能否提供您的输入和输出文档以及允许我们重现问题的代码？ 我们将检查问题并为您提供更多信息。

**Comment by xiaoxuhuicode** [comment]
你好，我已经重新提了issues 👍 https://github.com/aspose-words/Aspose.Words-for-.NET/issues/320

**Comment by AlexNosk** [comment]
The issue is moved to .NET category. Close.
