### ISSUE TITLE
Aspose.word function is missing

### ISSUE THREAD

**Issue by SnowflyW** [aspose-words/Aspose.Words-for-Java#86]
Aspose.word function is missing, and the picture set cannot output multiple pictures in the same table cell

**Comment by SnowflyW** [comment]
Suppose that there are two data sets, and each data corresponds to multiple pictures, the picture corresponding to the data cannot be achieved

**Comment by AlexNosk** [comment]
@SnowflyW Unfortunately, your request is not quite clear. Could you please elaborate your requirements in more details and attach your input document, sample data and the expected output? We will investigate and provide you more information.

**Comment by SnowflyW** [comment]
@AlexNosk 
Hello, alexnosk
My problem is that in the merge area, the data record is a list, and each data also contains multiple pictures. As a result, the pictures of each row of data are the same and repeated

![image](https://user-images.githubusercontent.com/30776452/181062908-ecfbe40c-0ab3-4ce3-adf2-44dc935090c7.png)
![image](https://user-images.githubusercontent.com/30776452/181063075-2ac92b14-7902-4600-8fd1-418c373ebee0.png)

**Comment by SnowflyW** [comment]
@AlexNosk 
Supplement:

The data source of non picture fields in the merge area is bound through datatable, and the picture circulates the following code in the following way:
```java
builder. moveToMergeField(fieldName, false, true);
builder. insertImage((BufferedImage) bufferedImage);
```
Then through the code, the field name of the dynamic control field (imglist1....imglist (n)), but the picture from 1... N lines is still repeated.

The first data record is a picture
The second data record is two pictures

**Comment by AlexNosk** [comment]
@SnowflyW I think in your case you can use [IFieldMergingCallback](https://reference.aspose.com/words/java/com.aspose.words/IFieldMergingCallback) to achieve that you need. For example here is a simple template example:
![image](https://user-images.githubusercontent.com/31235892/181191004-65e4ef38-98aa-413f-aedf-f83468a1d0b6.png)
And here is a code:
```java
Document doc = new Document("C:\\Temp\\in.docx");
doc.getMailMerge().setFieldMergingCallback(new MyFieldMergingCallback());
doc.getMailMerge().executeWithRegions(dt);
doc.save("C:\\Temp\\out.docx");
```
```java
private static class MyFieldMergingCallback implements IFieldMergingCallback
{
    @Override
    public void fieldMerging(FieldMergingArgs args) throws Exception {

        if(args.getFieldName().equals("ImgList"))
        {
            DocumentBuilder builder = new DocumentBuilder(args.getDocument());
            builder.moveToField(args.getField(), true);
            // And here insert images you need to insert.
            builder.insertImage("C:\\Temp\\" + args.getFieldValue());
            // If required you can insert more images here
            // .....
            // Since we already inserted data, set field value to empty string.
            args.setFieldValue("");
        }
    }

    @Override
    public void imageFieldMerging(ImageFieldMergingArgs args) throws Exception {
        // Do nothing.
        // however, you can use this method to insert image dynamically
        // if field name in the template is in format "Image:FieldName".
    }
}
```
The result of executing is the following:
![image](https://user-images.githubusercontent.com/31235892/181194164-6c9c9d06-9a2a-4cd4-b81b-b8dddb5c133c.png)

For your convenience here is input and output documents:
[in.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/9196283/in.docx)
[out.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/9196284/out.docx)

**Comment by SnowflyW** [comment]
@AlexNosk Thanks, brother
My English is not good. I use translation software
I also tried the image:mergefield method later, and it does not support outputting multiple pictures. It will only overwrite the previous pictures on the original field
In the callback event, loop builder.insert to try

**Comment by SnowflyW** [comment]
@AlexNosk 
I refer to the official documents and cases, so I always use the imagefieldmerging method in the ifieldmergegcallback interface, and replace it with fieldmerging method to achieve the effect I want. 
Thank you again, brother

The fieldmerging method corresponds to the merge field in the merge area of the word template.
The imagefieldmerging method corresponds to the < < image:xxxx > > field in the word template.

When using fieldmerging method, in special scenarios, you need to specify the field type of the next datatable column.

**Comment by AlexNosk** [comment]
@SnowflyW It looks like you managed to achieve what you need using `IFieldMergingCallback`. So I am closing the issue. Please feel free to open another one in case of any issues or post your question in our support forum <https://forum.aspose.com/c/words/8>

**Comment by SnowflyW** [comment]
@AlexNosk  OK 3Q
