### ISSUE TITLE
Invalid paragraph spacing setting

### ISSUE THREAD

**Issue by Wang0310** [aspose-words/Aspose.Words-for-Java#88]
![image](https://user-images.githubusercontent.com/5894924/181456165-7e0814f4-b34e-4f94-a81f-058203aa6521.png)
![image](https://user-images.githubusercontent.com/5894924/181456474-957cb781-8cf1-4726-b460-b9c47c15b9c0.png)

**Comment by AlexNosk** [comment]
@Wang0310 You are using `DocumentBuilder.insertHtml` method. By default content inserted from HTML ignores formatting specified in `DocumentBuilder`. You can use another overload of `DocumentBuilder.insertHtml` method to set a flag to use `DocumentBuilder` formatting:
```java
builder.insertHtml(
        "<p align='right'>Paragraph 1.</p>" +
                "<p>Paragraph 2.</p>", true);
```
<https://reference.aspose.com/words/java/com.aspose.words/documentbuilder#insertHtml(java.lang.String,boolean)>

**Comment by Wang0310** [comment]
@AlexNosk thank you. I've confirmed it. It's OK.
