### ISSUE TITLE
Missing text when convert word to pdf

### ISSUE THREAD

**Issue by liuyi520123** [aspose-words/Aspose.Words-for-Java#90]
I install specified fonts in windows and all text looks normal.
when i use aspose.word to convert, it missing most words, i upgrade aspose.word to 22.8, it also missing.

```
FontSettings fontSettings = new FontSettings();
fontSettings.setFontsFolder(FZ_FONTS_FOLDER, true);
fontSettings.getSubstitutionSettings().getDefaultFontSubstitution().setDefaultFontName("FZSongS-Extended");

document.getLayoutOptions().setTextShaperFactory(HarfBuzzTextShaperFactory.getInstance());

document.setFontSettings(fontSettings);

document.save(FZ_PDF_PATH, SaveFormat.PDF);
```

what can I do to make the pdf normal, thank you very much.

docx 
![image](https://user-images.githubusercontent.com/24844047/186662685-6aa25fbf-da70-43b7-9099-fed14039db6e.png)

pdf
![image](https://user-images.githubusercontent.com/24844047/186663463-89a93fe8-371d-4768-9c83-0025d295ebab.png)

I test it with program, the docx file and the font files are in program too.

it can download from [example](https://pan.baidu.com/s/1u9r_gOATXiQlilaCEl1LnA?pwd=2xt0).

**Comment by AlexNosk** [comment]
@liuyi520123 Unfortunately, I do not have baidu account. Could you please share the documents ad fonts on google drive? Also, please note Aspose.Words forum is the main place for support. So let's continue discussion in the forum:
<https://forum.aspose.com/t/missing-text-when-convert-word-to-pdf/251042>
