### ISSUE TITLE
fonts overlap using aspose

### ISSUE THREAD

**Issue by qulele123** [aspose-words/Aspose.Words-for-Java#93]
Use aspose.Word to convert PDF and Word use a variety of fonts. It is normal to export pdf directly using Word, but fonts overlap using aspose
![abnormal](https://user-images.githubusercontent.com/117641360/200292577-35383040-cc5c-4867-8b18-ec1b1f0f04b5.png)
use version of aspose-word-20.12  for java

**Comment by AlexNosk** [comment]
@qulele123 Could you please attach your document here for testing? we will check the issue and provide you more information.
The problem might occur because it is required to [enable open type features](https://docs.aspose.com/words/java/enable-opentype-features/).
