### ISSUE TITLE
reporting engine how to fill in content controls

### ISSUE THREAD

**Issue by earthskin** [aspose-words/Aspose.Words-for-Java#96]
```py
report = aw.reporting.ReportingEngine()
report.build_report(doc, test_data)
```
if doc has some `<<aaa>>` tag in content controls, data cann't fill in this content controls. 
how can i fill content controls with data?

**Comment by AlexNosk** [comment]
@earthskin Could you please attach your sample template and data here for testing? We will check the issue and provide you more information.
I have created a simple template with data placeholder in the main body and in the content control and both are properly filled with data. Please see the attached documents and the code: 
[in.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/10163034/in.docx)
[out.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/10163036/out.docx)
```py
doc = aw.Document("C:\\Temp\\in.docx");
engine = aw.reporting.ReportingEngine()
engine.build_report(doc, "This is my value", "value")
doc.save("C:\\Temp\\out.docx")
```
PS: placeholder should look like this `<<[aaa]>>`, not like this `<<aaa>>`.
