### ISSUE TITLE
如何在指定页面渲染目录

### ISSUE THREAD

**Issue by zhujinghuic** [aspose-words/Aspose.Words-for-Java#98]
如题，找不到对应方法

**Comment by AlexNosk** [comment]
@zhujinghuic 您能否更详细地阐述您的要求？ 请在 MS Word 中创建预期的输出文档并将其附在此处以供我们参考。 我们将对其进行检查并为您提供更多信息。

PS: 请注意获得支持的主要地点是 Aspose.Words 支持论坛。 请在那里发布您的问题。
<https://forum.aspose.com/c/words/8>
